### ISSUE TITLE
Организовать и залить проект Java 

### ISSUE THREAD

**Issue by ViRGiL175** [ViRGiL175/java-diner-automation#15]
Нужно начать разработку с проектных файлов проекта Java в среде IDEA 

## Описание

> Описание задачи, схемы, картинки и т.д. 

## Критерии выполненности 

- [x] Создан консольный проект Java с подключением библиотек RxJava и сериализации
- [x] Добавлен .gitignore для Java и для среды разработки JetBrains
- [x] Инициализирован репозиторий Git
- [x] Все залито в репозиторий GitHub 

## Связанное

> Всяческие подробности, ссылки, документация и т.д.

**Comment by ViRGiL175** [comment]
> *   с подключением библиотек

Тут все же почитай про Ant, Maven и Gradle.   
  
Я недавно читал как раз хорошую статью: https://www.baeldung.com/ant-maven-gradle  
  
Тут обозревается все. В Android используется Gradle и он более современный. Возможно, имеет смысл сразу создавать проект с ним и подключать библиотеки через него.

**Comment by EsQLap** [comment]
Сложность оказалась выше, чем я оценил. На 3 примерно тянет

**Comment by ViRGiL175** [comment]
Пока пулл реквест не принят, задача не закрывается.

Для автоматического линкования пулл реквеста к задаче юзается линкование: https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue
