### ISSUE TITLE
Организовать GitHub и Скрам-процесс

### ISSUE THREAD

**Issue by ViRGiL175** [ViRGiL175/java-diner-automation#16]
Освоение функционала GitHub и адаптация Скрама под него

## Описание

> Описание задачи, схемы, картинки и т.д. 

## Критерии выполненности 

- [ ] Составить удобный и функциональный README
- [x] Составить расписание в Google Calendar (расписание уроков, расписание мероприятий Скрам)
- [x] !!! Зайти !!! 
- [x] Оценить сложность задач скрам-мастера

## Связанное

> Всяческие подробности, ссылки, документация и т.д.

**Comment by ViRGiL175** [comment]
Ты можешь в Пулл Реквесте использовать ключевые слова, чтоб автоматически закрывать соответствующие Ишью: https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

**Comment by ViRGiL175** [comment]
Я добавил тебе еще задачу оценить сложность твоих задач. Пока попробуем личную оценку, а потом уже поиграем в покер планирования.

@Morgan-dev311

**Comment by tanya-dev413** [comment]
Посмотри README, пожалуйста.

@ViRGiL175

**Comment by ViRGiL175** [comment]
> Посмотри README, пожалуйста.
> 
> @ViRGiL175

Так, понял, ты теперь без Пулл Реквеста решила заливать. Тогда нужно удалить или закрыть https://github.com/ViRGiL175/java-diner-automation/pull/11

Ридми отличный, добавь еще прямые ссылки на наши материалы для удобства, как я упомянул тут: https://github.com/ViRGiL175/java-diner-automation/issues/22#issuecomment-705750779

Например, я оформляю ссылки так: 
![image](https://user-images.githubusercontent.com/11541555/95500019-3c48c800-09b7-11eb-972e-415b1838b698.png)

**Comment by tanya-dev413** [comment]
Готово.
