### ISSUE TITLE
Кратко описать Скрам-стратегию по разработке

### ISSUE THREAD

**Issue by ViRGiL175** [ViRGiL175/java-diner-automation#18]
Каждый должен иметь точное представление о Скрам-процессе, который у нас происходит

## Описание

Мы начинали об этом говорить, у тебя даже были соответствующие заготовки.

Поможет всем одинаково представлять процесс разработки, а тебе -- вести чек-лист, чтоб ничего не забыть.
Например, сегодня забыли оценить сложность, хотя планировали, и т.д.

Можешь тут же расписать тайминги наших мероприятий, дейли митинги и прочие планнинги не должны быть длинными и т.д.

Все по книге. 

Можешь дать ссылки на краткие и емкие ресурсы, куда можно подглядывать Егору про Скрам, например такие: https://habr.com/ru/post/464861/

Но в первую очередь просвещение исходит от тебя. 

Оформить можно как Ишью, но трудно будет редактировать, редактор тут не очень, или как Марк-даун файл, который можно редачить через тот же https://stackedit.io/. 

Тут смотри сама.

## Критерии выполненности 

- [x] У нас есть небольшой, но емкий документ, где можно быстро понять, как мы работаем 

## Связанное

> Всяческие подробности, ссылки, документация и т.д.

**Comment by ViRGiL175** [comment]
> можно редачить через тот же https://stackedit.io/.

![image](https://user-images.githubusercontent.com/11541555/94993680-d1a52000-05a3-11eb-9075-bde0dd04d5ce.png)

Редактор удобный, но надо его немного настраивать, когда коннектишь к ГитХабу.

**Comment by tanya-dev413** [comment]
Создала новый issue с меткой `type:_documentation`. В нем - скрам-стратегия по разработке.
