### ISSUE TITLE
Освоить Git и GitHub

### ISSUE THREAD

**Issue by ViRGiL175** [ViRGiL175/java-diner-automation#2]
На начальном уровне ориентироваться в Git и GitHub 

## Описание

Все обсуждали вживую.

![image](https://user-images.githubusercontent.com/11541555/93689678-d10b8480-fae1-11ea-8bdf-add8bc1c2282.png)

## Критерии выполненности 

- [x] Прочитать обозначенные главы [ProGit](https://git-scm.com/book/ru/v2)
- [x] Пройти https://learngitbranching.js.org/

## Связанное

> Всяческие подробности, ссылки, документация и т.д.

**Comment by EsQLap** [comment]
learngitbranching.js.org - невероятно крутая штука! Мне очень понравилось. Всё на своих местах в голове теперь)
