### ISSUE TITLE
Освоить сериализацию JSON в Java

### ISSUE THREAD

**Issue by ViRGiL175** [ViRGiL175/java-diner-automation#3]
Научиться сериализовывать и десериализовывать JSON объекты 

## Описание

Очень популярная технология, нужна везде, облегчает многие вещи при разработке и проектировании.

![image](https://user-images.githubusercontent.com/11541555/93689798-15e3eb00-fae3-11ea-8de5-f485da8445f7.png)

## Критерии выполненности 

- [x] Изучить популярные библиотеки для сериализации
- [x] Выбрать библиотеку для работы
- [x] Освоить библиотеку и особенности её работы

## Связанное

> Всяческие подробности, ссылки, документация и т.д.

**Comment by ViRGiL175** [comment]
![](https://user-images.githubusercontent.com/11541555/93716094-94da3180-fb7e-11ea-847c-9579e0760bad.png)

**Comment by ViRGiL175** [comment]
В итоге Gson? Разобрался, как работает?   
  
Перебрал другие либы? В чем разница, например, с Moshi?

**Comment by EsQLap** [comment]
Я так понял, Gson медленнее и зачастую генерирует непредвиденные исключения, однако полезной информации о нем я нашёл больше, чем о других. Поэтому решил выбрать его. Подумывал как раз о Moshi, ведь на андроиде будем работать, а она как раз для него. Но чего-то туторов маловато нашлось.

**Comment by ViRGiL175** [comment]
Еще в Gson больше предсозданных адаптеров для сериализации разных моделей данных, типа даты и времени. А Moshi про такие модели данных не знает, они в него не встроены, он их сериализовать по-умолчанию не умеет. Можно написать свои адаптеры, или пользоваться плагинами.  
  
Еще Moshi хорошо работает в связке с другими библиотеками на движке потоков Okko. Это, например, Retrofit, важная штука. Если у тебя стек на Okko, то выгоднее брать Moshi.   
  
Но для начала Gson реально лучше подойдет, юзай.
