### ISSUE TITLE
Поделиться опытом по Git и Scrum

### ISSUE THREAD

**Issue by ViRGiL175** [ViRGiL175/java-diner-automation#30]
Нужно равномерно распределять опыт внутри команды

## Описание

У Scrum и Git сложные необычные философии и парадигмы, просто так работать в них не начнешь.

Очень важно не просто им следовать, как будто соблюдаешь [карго-культ](https://ru.wikipedia.org/wiki/Карго-культ), а понимать, почему делается именно так и какие преимущества такие подход дает.

Вы можете созваниваться вместе, встречаться, подключать меня на эти встречи/звонки и т. д. Сейчас важно в двух этих парадигмах всем настроиться на одну волну.

И помните, особенно касательно Git, чтение книг и статей без практике не дает ничего, получается полный ноль. Только вместе с практикой. 

## Критерии выполненности 

- [x] Егор понимает и разделяет базовые принципы и ценности Scrum 
- [x] Егор понимает Scrum-процесс 
- [x] Таня понимает и разделяет базовые принципы подхода Git и GitHub
- [x] Таня может проводить базовые операции с Git и GitHub 

## Связанное

> Всяческие подробности, ссылки, документация и т.д.

**Comment by tanya-dev413** [comment]
Таня и Егор молодцы!
