### ISSUE TITLE
Освоить RxJava 

### ISSUE THREAD

**Issue by ViRGiL175** [ViRGiL175/java-diner-automation#4]
Познакомиться с технологией реактивного программирования ReactiveX 

## Описание

Довольно сложная технология, но она важна для безболезненного проектирования сложных систем.

Отдельно приятно, что оно нативно интегрировано со стандартной библиотекой Java.

![image](https://user-images.githubusercontent.com/11541555/93689974-a7079180-fae4-11ea-8eea-dae31844a1ab.png)

## Критерии выполненности 

- [x] Подобрать статьи по RxJava и реактивной технологии
- [x] Освоить подобранные статьи
- [x] Отдельно разобрать паттерн Observer и почитать про паттерны проектирования в целом
- [x] Попробовать RxJava на практике 

## Связанное

> Всяческие подробности, ссылки, документация и т.д.

**Comment by ViRGiL175** [comment]
При подборе статей кидай их, можно даже в общий чат, я посмотрю и одобрю и не одобрю то, что ты нарыл.  
  
Нужно учиться копать техническую документацию по новым фишкам.  
  
@EsQLap

**Comment by EsQLap** [comment]
Что подразумевается под пунктом "Попробовать RxJava на практике?"

**Comment by ViRGiL175** [comment]
> Что подразумевается под пунктом "Попробовать RxJava на практике?"

Все, что ты читаешь в статьях, референсе и прочем, если не попробовать запустить, поэкспериментировать с этим, не имеет смысла, не отложится в голове, не поймется на самом деле, забудется через час.

**Comment by EsQLap** [comment]
Да, помню, мы говорили об этом. Просто подумал, может, тут есть какие-то задачи, которые нам будет нужно обсудить.
