### ISSUE TITLE
Красивый лог

### ISSUE THREAD

**Issue by tanya-dev413** [ViRGiL175/java-diner-automation#74]
Для удобства дальнейшей разработки нужно разбить все процессы дайнера на группы. Стандарт логирования Java.

## Описание

> Описание задачи, схемы, картинки и т.д. 

## Критерии выполненности 

- [x] Используется стандарт логгирования Java
- [x] Найдена библиотека
- [x] Лог хорошо читается
- [x] Выводимые данные хорошо структурированы

## Связанное

> Всяческие подробности, ссылки, документация и т.д.

**Comment by tanya-dev413** [comment]
@ViRGiL175 Не знаю, как формулировать и чего писать в критерии выполненности

**Comment by ViRGiL175** [comment]
> @ViRGiL175 Не знаю, как формулировать и чего писать в критерии выполненности

Все ок, критерии дописал.

Можно выводить данные как JSON и использвоать всяческие `pretty`: https://stackoverflow.com/questions/35026581/json-formatting-with-moshi

А можно придумать другой формат вывода. Главное чтоб у человека глаза не плавились от лога. @EsQLap
