### ISSUE TITLE
Вывод буквы "И"

### ISSUE THREAD

**Issue by EsQLap** [ViRGiL175/java-diner-automation#78]
Вместо заглавной буквы "И" выводятся неопознанные символы

**Как воcпроизвести**

Попытаться вывести заглавную "И" на экран

**Ожидаемое поведение**

Вывод "И"

**Скриншоты и схемы**

![Буква И](https://user-images.githubusercontent.com/61599652/97106415-e70cf600-16da-11eb-8c2e-15cef137ebb7.png)

**Comment by ViRGiL175** [comment]
Пофикшено в #91

**Comment by Morgan-dev311** [comment]
Пофикшено в #91
